services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /downloading/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/radarr:/config # Example, change to your local pathing
      - /SharedVideos:/data # Example, change to your local pathing
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/sonarr:/config # Example, change to your local pathing
      - /SharedVideos:/data # Example, change to your local pathing
    ports:
      - 8989:8989
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  qbittorrentvpn:
    container_name: qbittorrentvpn
    image: binhex/arch-qbittorrentvpn:latest
    restart: unless-stopped
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8080:8080/tcp
      - 8118:8118/tcp
    privileged: true
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # Change to your timezone
      - UMASK=022
      - DEBUG=false
      - VPN_ENABLED=yes
      - VPN_USER= # change to your username
      - VPN_PASS= # Change to your password
      - VPN_PROV=pia
      - STRICT_PORT_FORWARD=yes
      - LAN_NETWORK=192.168.200.0/24,192.168.201.0/24,192.168.202.0/24,192.168.203.0/24 # example "LAN_NETWORK=192.168.0.0/24"
      - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
      - WEBUI_PORT=8080 # port for web interfance
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/qbittorent/openvpn:/config:rw # Change "/docker/appdata/qbittorrentvpn" with the path your config will be.
      - /SharedVideos:/data:rw # Change "/data/torrents" with the path your torrent data ends up in.
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/jellyfin:/config
      - /SharedVideos/tvshows:/data/tvshows # Example, change to your local pathing
      - /SharedVideos/movies:/data/movies # Example, change to your local pathing
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /docker/bazarr/config:/config
      - /SharedVideos/movies:/data/movies #optional
      - /SharedVideos/tvshows:/data/tvshows #optional
    ports:
      - 6767:6767
    restart: unless-stopped